# Generated by Django 2.1.15 on 2023-03-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('personid', models.AutoField(db_column='PersonID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, db_column='Item_type', max_length=255, null=True)),
                ('sales_channel', models.CharField(blank=True, db_column='Sales_Channel', max_length=255, null=True)),
                ('order_priority', models.CharField(blank=True, db_column='Order_Priority', max_length=255, null=True)),
                ('order_date', models.DateTimeField(blank=True, db_column='Order_Date', null=True)),
                ('order_id', models.IntegerField(blank=True, db_column='Order_ID', null=True)),
                ('ship_date', models.DateTimeField(blank=True, db_column='Ship_Date', null=True)),
                ('units_sold', models.IntegerField(blank=True, db_column='Units_Sold', null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='Unit_Price', null=True)),
                ('unit_cost', models.FloatField(blank=True, db_column='Unit_Cost', null=True)),
                ('total_revenue', models.FloatField(blank=True, db_column='Total_Revenue', null=True)),
                ('total_cost', models.FloatField(blank=True, db_column='Total_Cost', null=True)),
                ('total_profit', models.FloatField(blank=True, db_column='Total_Profit', null=True)),
            ],
            options={
                'db_table': 'sales_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('emailid', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'studentdata',
                'managed': False,
            },
        ),
    ]
